package com.rafsan.newsapp.feature.news.model

data class Country(
    val code: String,
    val name: String
)

val supportedCountries = listOf(
    Country("us", "United States"),
    Country("gb", "United Kingdom"),
    Country("ca", "Canada"),
    Country("au", "Australia"),
    Country("de", "Germany"),
    Country("fr", "France"),
    Country("in", "India"),
    Country("jp", "Japan"),
    Country("cn", "China"),
    Country("ru", "Russia"),
    Country("br", "Brazil"),
    Country("za", "South Africa"),
    Country("kr", "South Korea"),
    Country("ae", "United Arab Emirates"),
    Country("ar", "Argentina"),
    Country("at", "Austria"),
    Country("be", "Belgium"),
    Country("bg", "Bulgaria"),
    Country("ch", "Switzerland"),
    Country("co", "Colombia"),
    Country("cu", "Cuba"),
    Country("cz", "Czech Republic"),
    Country("eg", "Egypt"),
    Country("gr", "Greece"),
    Country_("hk", "Hong Kong"),
    Country("hu", "Hungary"),
    Country("id", "Indonesia"),
    Country("ie", "Ireland"),
    Country("il", "Israel"),
    Country("it", "Italy"),
    Country("lt", "Lithuania"),
    Country("lv", "Latvia"),
    Country("ma", "Morocco"),
    Country("mx", "Mexico"),
    Country("my", "Malaysia"),
    Country("ng", "Nigeria"),
    Country("nl", "Netherlands"),
    Country("no", "Norway"),
    Country("nz", "New Zealand"),
    Country("ph", "Philippines"),
    Country("pl", "Poland"),
    Country("pt", "Portugal"),
    Country("ro", "Romania"),
    Country("rs", "Serbia"),
    Country("sa", "Saudi Arabia"),
    Country("se", "Sweden"),
    Country("sg", "Singapore"),
    Country("si", "Slovenia"),
    Country("sk", "Slovakia"),
    Country("th", "Thailand"),
    Country("tr", "Turkey"),
    Country("tw", "Taiwan"),
    Country("ua", "Ukraine"),
    Country("ve", "Venezuela"),
)
